/*
 * ServerManage.java
 *
 * Created on __DATE__, __TIME__
 */

package com.bsb.UIdesign;

import java.awt.Font;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

import javax.swing.*;

import com.handplan.testmysetversocket.main.MyServerSocket;
import com.handplan.testmysetversocket.main.ServerListener;

/**
 * 
 * @author __USER__
 */
public class ServerManage extends JFrame {
	ServerListener serv = null;

	/** Creates new form ServerManage */
	public ServerManage() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new JLabel();
		jScrollPane1 = new JScrollPane();
		jTextArea1 = new JTextArea();
		jButton1 = new JButton();
		jButton2 = new JButton();

		setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

		jLabel1.setFont(new Font("Microsoft YaHei UI", 1, 18));
		jLabel1.setHorizontalAlignment(SwingConstants.CENTER);
		jLabel1.setText("\u670d\u52a1\u5668\u754c\u9762");
		jTextArea1.setEditable(false);
		jTextArea1.setColumns(20);
		jTextArea1.setRows(5);
		jTextArea1.setLineWrap(true); // 激活自动换行功能
		jTextArea1.setWrapStyleWord(true); // 激活断行不断字功能

		jScrollPane1.setViewportView(jTextArea1);

		jButton1.setText("\u542F\u52A8\u670D\u52A1\u5668");

		jButton2.setText("\u505c\u6b62\u670d\u52a1\u5668");
		jButton1.addMouseListener(new MouseAdapter() {

			@Override
			public void mouseClicked(MouseEvent e) {
				// TODO Auto-generated method stub
				serv = new ServerListener();
				serv.start();
				jTextArea1.append("已经开启服务器" + "\n");
				jButton1.setEnabled(false);
			}

		});
		jButton2.addMouseListener(new MouseAdapter() {

			@Override
			public void mouseClicked(MouseEvent e) {
				// TODO Auto-generated method stub
				if (serv != null) {
					serv.stop();
					JOptionPane.showMessageDialog(null, "服务器断开", "【提示】",
							JOptionPane.INFORMATION_MESSAGE);
					jButton1.setEnabled(true);
				} else {
					JOptionPane.showMessageDialog(null, "未启动服务器，不能关闭", "【出错啦】",
							JOptionPane.ERROR_MESSAGE);
				}
			}

		});
		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(layout
						.createSequentialGroup()
						.add(layout
								.createParallelGroup(
										org.jdesktop.layout.GroupLayout.LEADING)
								.add(layout
										.createSequentialGroup()
										.add(59, 59, 59)
										.add(layout
												.createParallelGroup(
														org.jdesktop.layout.GroupLayout.LEADING,
														false)
												.add(org.jdesktop.layout.GroupLayout.TRAILING,
														layout.createSequentialGroup()
																.add(jButton1,
																		org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																		107,
																		org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		org.jdesktop.layout.LayoutStyle.RELATED,
																		org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE)
																.add(jButton2,
																		org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																		116,
																		org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
												.add(org.jdesktop.layout.GroupLayout.TRAILING,
														jScrollPane1,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
														276,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
								.add(layout
										.createSequentialGroup()
										.add(109, 109, 109)
										.add(jLabel1,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												182,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
						.addContainerGap(90, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(layout
						.createSequentialGroup()
						.add(8, 8, 8)
						.add(jLabel1,
								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
								51,
								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
						.add(8, 8, 8)
						.add(layout
								.createParallelGroup(
										org.jdesktop.layout.GroupLayout.BASELINE)
								.add(jButton2).add(jButton1))
						.addPreferredGap(
								org.jdesktop.layout.LayoutStyle.UNRELATED)
						.add(jScrollPane1,
								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
								162,
								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
						.add(36, 36, 36)));

		pack();
	}// </editor-fold>
		// GEN-END:initComponents

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				ServerManage sm = new ServerManage();
				sm.setVisible(true);
				ServerConManage.getCM().setWindow(sm);
			}
		});
	}

	public void appendTextother(String in) {

		jTextArea1.append("\n" + in);

	}

	//定义控件
	private JButton jButton1;
	private JButton jButton2;
	private JLabel jLabel1;
	private JScrollPane jScrollPane1;
	private JTextArea jTextArea1;

}